#!/bin/bash

echo "GitHub Actions Self-Hosted Runner Setup"
echo "======================================="
echo ""
echo "To set up a self-hosted runner on this machine:"
echo ""
echo "1. Go to your GitHub repository"
echo "2. Navigate to Settings > Actions > Runners"
echo "3. Click 'New self-hosted runner'"
echo "4. Choose 'Linux' and follow the instructions"
echo ""
echo "Or run these commands (replace YOUR_TOKEN with the token from GitHub):"
echo ""
echo "# Create a folder for the runner"
echo "mkdir -p ~/actions-runner && cd ~/actions-runner"
echo ""
echo "# Download the latest runner package"
echo "curl -o actions-runner-linux-x64-2.319.1.tar.gz -L https://github.com/actions/runner/releases/download/v2.319.1/actions-runner-linux-x64-2.319.1.tar.gz"
echo ""
echo "# Extract the installer"
echo "tar xzf ./actions-runner-linux-x64-2.319.1.tar.gz"
echo ""
echo "# Configure (replace YOUR_TOKEN and YOUR_REPO)"
echo "./config.sh --url https://github.com/YOUR_USERNAME/YOUR_REPO --token YOUR_TOKEN"
echo ""
echo "# Run as a service"
echo "sudo ./svc.sh install"
echo "sudo ./svc.sh start"
echo ""
echo "======================================="
echo ""
echo "Since this runner will be on your local network, it can access 'apps' server directly!"