#!/bin/bash

echo "GitHub Actions Deployment Setup"
echo "==============================="
echo ""
echo "You need to add the following secrets to your GitHub repository:"
echo ""
echo "1. Go to your GitHub repository: https://github.com/[your-username]/umbral-nexus"
echo "2. Navigate to Settings > Secrets and variables > Actions"
echo "3. Add these repository secrets:"
echo ""
echo "DEPLOY_SSH_KEY:"
echo "---------------"
cat ~/.ssh/id_ed25519
echo ""
echo ""
echo "DEPLOY_HOST: apps"
echo "DEPLOY_USER: $USER"
echo ""
echo "==============================="
echo ""
echo "SSH Public Key to add to the 'apps' server:"
echo "-------------------------------------------"
echo "Copy this key and add it to ~/.ssh/authorized_keys on the 'apps' server:"
echo ""
cat ~/.ssh/id_ed25519.pub
echo ""
echo ""
echo "To add the key to the apps server, you can run:"
echo "ssh-copy-id -i ~/.ssh/id_ed25519 $USER@apps"
echo ""
echo "Or manually add it by:"
echo "1. SSH into the apps server"
echo "2. Add the above public key to ~/.ssh/authorized_keys"