name: umbral-nexus
services:
  umbral-nexus:
    image: ghcr.io/zbonzo/umbralnexus/server:latest
    container_name: umbral-nexus
    restart: unless-stopped
    ports:
      - target: 80
        published: 8888
        protocol: tcp
    environment:
      NODE_ENV: production
      PORT: 3000
      MONGODB_URI: mongodb://umbral-nexus-db:27017/umbral-nexus
      REDIS_URL: redis://umbral-nexus-redis:6379
      CORS_ORIGIN: http://cosmos:8888
    volumes:
      - type: bind
        source: /DATA/AppData/umbral-nexus/config
        target: /app/config
      - type: bind
        source: /DATA/AppData/umbral-nexus/client
        target: /usr/share/nginx/html
    depends_on:
      - umbral-nexus-db
      - umbral-nexus-redis
    networks:
      - umbral-nexus-network
    x-casaos:
      ports:
        - container: "80"
          description:
            en_us: "Web UI Port"
      volumes:
        - container: /app/config
          description:
            en_us: "Config directory"
        - container: /usr/share/nginx/html
          description:
            en_us: "Client build files"

  umbral-nexus-db:
    image: mongo:7.0
    container_name: umbral-nexus-db
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: umbral-nexus
    volumes:
      - type: volume
        source: umbral-nexus-db-data
        target: /data/db
    networks:
      - umbral-nexus-network
    x-casaos:
      volumes:
        - container: /data/db
          description:
            en_us: "MongoDB data"

  umbral-nexus-redis:
    image: redis:7-alpine
    container_name: umbral-nexus-redis
    restart: unless-stopped
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    volumes:
      - type: volume
        source: umbral-nexus-redis-data
        target: /data
    networks:
      - umbral-nexus-network
    x-casaos:
      volumes:
        - container: /data
          description:
            en_us: "Redis data"

volumes:
  umbral-nexus-db-data:
    name: umbral-nexus-db-data
  umbral-nexus-redis-data:
    name: umbral-nexus-redis-data

networks:
  umbral-nexus-network:
    name: umbral-nexus-network

x-casaos:
  architectures:
    - amd64
    - arm64
  main: umbral-nexus
  author: Umbral Nexus Team
  category: Games
  description:
    en_us: A cooperative roguelike dungeon crawler for 1-20 players. Use smartphones as controllers while viewing the game on a shared screen.
  developer: Umbral Nexus Team
  icon: https://raw.githubusercontent.com/yourusername/umbral-nexus/main/icon.png
  index: /
  port_map: "8888"
  scheme: http
  store_app_id: umbral-nexus
  tagline:
    en_us: Cooperative Roguelike Adventure
  thumbnail: https://raw.githubusercontent.com/yourusername/umbral-nexus/main/thumbnail.png
  title:
    en_us: Umbral Nexus
  tips:
    before_install:
      en_us: |
        Default port is 8888. Make sure this port is available.
        Game requires smartphones for controllers - ensure devices are on same network.