name: Deploy to Self-Hosted Server

on:
  push:
    branches: [master]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-deploy:
    name: Build and Deploy to Apps Server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm install --legacy-peer-deps
      
      - name: Build all packages
        run: npm run build
      
      - name: Build Docker image
        run: |
          docker build -f Dockerfile.production -t umbralnexus-server:latest .
      
      - name: Save Docker image
        run: |
          docker save umbralnexus-server:latest | gzip > umbralnexus-server.tar.gz
      
      - name: Deploy to Apps Server
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
        run: |
          # Set up SSH
          mkdir -p ~/.ssh
          echo "$DEPLOY_KEY" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H $DEPLOY_HOST >> ~/.ssh/known_hosts
          
          # Copy Docker image to apps server
          scp -i ~/.ssh/deploy_key umbralnexus-server.tar.gz $DEPLOY_USER@$DEPLOY_HOST:/tmp/
          
          # Copy docker-compose file
          scp -i ~/.ssh/deploy_key docker-compose.portainer.yml $DEPLOY_USER@$DEPLOY_HOST:/tmp/docker-compose.yml
          
          # Deploy on apps server
          ssh -i ~/.ssh/deploy_key $DEPLOY_USER@$DEPLOY_HOST << 'ENDSSH'
            # Load Docker image
            docker load < /tmp/umbralnexus-server.tar.gz
            
            # Create deployment directory
            mkdir -p ~/umbral-nexus
            
            # Move docker-compose file
            mv /tmp/docker-compose.yml ~/umbral-nexus/
            
            # Go to deployment directory
            cd ~/umbral-nexus
            
            # Stop existing containers
            docker-compose down --remove-orphans || true
            
            # Start services
            docker-compose up -d
            
            # Clean up
            rm -f /tmp/umbralnexus-server.tar.gz
            
            # Show status
            docker-compose ps
            docker-compose logs --tail=50
          ENDSSH
      
      - name: Clean up
        if: always()
        run: |
          rm -f ~/.ssh/deploy_key
          rm -f umbralnexus-server.tar.gz